### ISSUE TITLE
Have you considered moving this repository under the gPodder organization?

### ISSUE THREAD

**Issue by adamvoss** [gpodder/gpodder-osx-bundle#11]
I didn't know this project existed and was an integral part of gPodder releases until gpodder/gpodder#320.  Clearly you are the maintainer of this project, and perhaps the solution is just to add more links to this project in documentation.

However, I was wondering if you had considered moving the project into the [gPodder](https://github.com/gpodder/) organization?  That way it would appear with the other gPodder related repositories when people look at the organization page.

**Comment by elelay** [comment]
Yes. This should definitely happen.
Transferring now (fingers crossed)...

**Comment by elelay** [comment]
@thp, I'm not allowed to create repositories in gpodder organization.
Can you raise my privileges so that I can transfer gpodder-osx-bundle to gpodder?

**Comment by thp** [comment]
@elelay try again now

**Comment by elelay** [comment]
Done, thanks!
