### ISSUE TITLE
Command-line interface does not seem to be included

### ISSUE THREAD

**Issue by dnivi3** [gpodder/gpodder-osx-bundle#12]
Running `gpo` in Terminal results in `command not found: gpo`. 

I have gPodder installed via homebrew cask, they pull gPodder from SourceForge it appears: https://github.com/caskroom/homebrew-cask/blob/master/Casks/gpodder.rb

The command-line interface should be included with the package and possible to use as described here: https://gpodder.github.io/docs/user-manual.html#command-line-interface

**Comment by elelay** [comment]
It's bundled in the gPodder.app.
You should be able to run it using the full path `/whatever/homebrew/installs/to/gPodder.app/Contents/MacOS/gpo`

Once you confirm it works, you could add /whatever/homebrew/installs/to/gPodder.app/Contents/MacOS/ to your PATH permanently.
