### ISSUE TITLE
Gatekeeper signing on macOS

### ISSUE THREAD

**Issue by Keeblo** [gpodder/gpodder-osx-bundle#15]
gPodder for macOS is currently not signed, so Gatekeeper displays a warning/error message when users attempt to run the application. This prevents gPodder from being used in environments where users are not permitted to disable Gatekeeper.

Is it possible to get gPodder signed? Thank you :-)

**Comment by elelay** [comment]
Thanks for your comment.
I don't plan to do this until apple makes installing unsigned apps impossible.
Maybe then I'll just stop supporting macOS...
