### ISSUE TITLE
gpodder_dont_check_display.patch is no longer needed

### ISSUE THREAD

**Issue by auouymous** [gpodder/gpodder-osx-bundle#18]
https://github.com/gpodder/gpodder/pull/984 bypasses the DISPLAY check if gpodder.ui.osx, removing the need for this patch. I could probably remove the file myself but won't because I have no way to test it.

https://github.com/gpodder/gpodder-osx-bundle/blob/master/modulesets/patches/gpodder_dont_check_display.patch

**Comment by elelay** [comment]
okay. Good to remove!
